Update index.tsx
codeforpdx/recordexpungPDX pull request #1590
Opened 2022-01-27 21:42 UTC by michaelzhang43

Updated to reflect new forms

2022-01-28 03:48 UTC, hmarcks requested changes
Just a couple of markup fixes

2022-01-28 03:48 UTC, hmarcks commented on src/frontend/src/components/Manual/index.tsx
> +
```suggestion
                charges. RecordSponge will also generate a Request form to Oregon
                State Police. You will need to complete this form manually and mail 
                a completed copy to Oregon State Police at:
                <span className="db pt2">
                  Oregon State Police, CJIS – Unit 11<br>
                  ATTN: SET ASIDE<br>
                  P.O. Box 4395<br>
                  Portland, OR 97208-4395<br>
                </span>
```

2022-01-28 03:48 UTC, hmarcks commented on src/frontend/src/components/Manual/index.tsx
> +              </p>
```suggestion
              <p className="mb3">
                If you are seeking expungement of at least one conviction, you 
                will need to include a check or money order made out to 
                "Oregon State Police" for $33.
              </p>
```

2022-01-29 18:12 UTC, hmarcks commented
@wittejm @KentShikama let me know if these suggestions look okay and I can commit them, thanks

2022-01-29 18:30 UTC, KentShikama commented
@hmarcks Yup looks good

2022-01-29 22:36 UTC, hmarcks approved these changes

2022-01-29 22:36 UTC, merged